// Generated by scripts/gen-sw.mjs — do not edit by hand.
// Offline shell for Fallow. Caches the app's own files only; no user content
// passes through here, and there is no push registration of any kind.

const CACHE = 'fallow-Li9hcHBsZS10b3Vj';
const ASSETS = [
  "./apple-touch-icon.png",
  "./assets/busy-but-fine-nNmapEZL.js",
  "./assets/drought-Dl-AFGsL.js",
  "./assets/index-BMH0xCyA.css",
  "./assets/index-CfIi2qT0.js",
  "./assets/nunito-latin-BzFMHfZw.woff2",
  "./assets/nunito-latin-ext-CXYtwYOx.woff2",
  "./assets/shift-C_LC4ZMK.js",
  "./assets/sparse-Co_1YTGE.js",
  "./favicon-32.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-512.png",
  "./icon.svg",
  "./index.html",
  "./manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // Navigations: try the network so an update lands, fall back to the cached
  // shell when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html').then((r) => r ?? caches.match('./'))),
    );
    return;
  }

  // Everything else: cache first — the assets are content-hashed.
  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ??
        fetch(request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(request, copy));
          }
          return res;
        }),
    ),
  );
});
