// Generates dist/sw.js after a build, precaching the built assets so the app
// opens with no network at all. Nothing is ever sent anywhere — this only
// caches the app's own files. Run automatically by `npm run build`.

import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const dist = 'dist';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const files = walk(dist)
  .map((p) => './' + relative(dist, p).split('\\').join('/'))
  .filter((p) => !p.endsWith('sw.js'));

// Cache name changes whenever the asset list does, so an update replaces the
// old cache instead of layering on it.
const version = Buffer.from(files.join('|')).toString('base64url').slice(0, 16);

const sw = `// Generated by scripts/gen-sw.mjs — do not edit by hand.
// Offline shell for Fallow. Caches the app's own files only; no user content
// passes through here, and there is no push registration of any kind.

const CACHE = 'fallow-${version}';
const ASSETS = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // Navigations: try the network so an update lands, fall back to the cached
  // shell when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html').then((r) => r ?? caches.match('./'))),
    );
    return;
  }

  // Everything else: cache first — the assets are content-hashed.
  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ??
        fetch(request).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(request, copy));
          }
          return res;
        }),
    ),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);

// GitHub Pages serves from a subpath and 404s on deep links; a copy of
// index.html as 404.html keeps refreshes working.
writeFileSync(join(dist, '404.html'), readFileSync(join(dist, 'index.html')));

console.log(`sw.js written (${files.length} assets, cache fallow-${version})`);
